"""add user volume & text_size

Revision ID: 6a535270795b
Revises: 51ea91cdf5ef
Create Date: 2025-06-07 04:21:52.056451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a535270795b'
down_revision = '51ea91cdf5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'volume',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('100')
        ))
        batch_op.add_column(sa.Column(
            'text_size',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('100')
        ))
    # remove server defaults if you like
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('volume', server_default=None)
        batch_op.alter_column('text_size', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('text_size')
        batch_op.drop_column('volume')

    # ### end Alembic commands ###
